### PR TITLE
Update old transaction's txID

### PR DESCRIPTION
**Pull request by chendatony31**
In the `alterTransaction` function, it has updated transaction content(data or extension), but not the TXid, it causes the old transaction to be invalid.  (The new Transaction is valid though)

### CODE REVIEW

**Comment by llwslc** [comment]
Thanks for bringing this over!

**Comment by llwslc** [comment]
Why do you need to update old transactions?

**Comment by chendatony31** [comment]
In `addUpdateData` function if you don't pass a `callback`,  it will be meaningless.

**Comment by llwslc** [comment]
Thanks for the feedback. I just tested it. Here is my code. It returns the correct txid. Can you show me your code?

```
  const transaction = await tronWeb.transactionBuilder.sendTrx(userAddress, 1);
  const newTransaction = await tronWeb.transactionBuilder.addUpdateData(transaction, 'note');

  console.log('before', transaction);
  console.log('after', newTransaction);
```

**Comment by chendatony31** [comment]
Yeah, it works using the newTransaction. But maybe it is not clearly stated in the documentation (https://developers.tron.network/reference/addupdatedata),  developers don't know they need to use the new Transaction.

The case here: https://fans.tokenpocket.pro/t/topic/15534/11

And tronlink wallet works because they replace the user's old transaction by default when signing any tx, which we think is not a good way

**Comment by llwslc** [comment]
I see, but replacing the txid is not enough. Thanks for the improvement.

**Comment by chendatony31** [comment]
Oh yes, as the txid is generated by raw_data_hex, so replacing the `raw_data_hex` is also needed. And what's more, maybe these changes could be done offline instead of an RPC call?

**Pull request merged**
