### PR TITLE
Large refactoring to reduce the size of TronWeb

### PR DESCRIPTION
**Pull request by sullof**
The goals of this release:

- [x] Compacting TronWeb getting rid of Ethers.js
- [x] Set up TronGridJS integration

### CODE REVIEW

**Comment by summertanh** [comment]
@sullof Hi, we've reviewed the code, we think that getting rid of etherjs is a good performance to reduce the size of tronweb . However, we wonder why import the new library 'bn.js',  as bignumber.js  already exists.

**Comment by sullof** [comment]
I left Tron in January. Before I was the head of the dev tools, i.e., I was responsible for Tronweb, Tronbox, Trongrid, etc. The reason why the description was so small is because the team knew about it. I should have merged it before leaving. I am quite shocked that, since one of the biggest problems of TronWeb was the side, this PR has not been merged. 
Thus said, I used `bn.js` because I reused the trick used in Ethers to manage big numbers and the two libraries manages some details in a very different way. The idea was to improve it in a future PR with further optimizations.

**Comment by xrdavies** [comment]
> I left Tron in January. Before I was the head of the dev tools, i.e., I was responsible for Tronweb, Tronbox, Trongrid, etc. The reason why the description was so small is because the team knew about it. I should have merged it before leaving. I am quite shocked that, since one of the biggest problems of TronWeb was the size, this PR has not been merged.
> Thus said, I used `bn.js` because I reused the trick used in Ethers to manage big numbers and the two libraries manages some details in a very different way. The idea was to improve it in a future PR with further optimizations.

Seems not able to be merged. But indeed it solves lots of problem with smaller size.

**Comment by sullof** [comment]
I see the conflicts. I will take a look in the coming days if I have a moment and fix them.

**Comment by summertanh** [comment]
Thanks, we will support this in next version.

**Pull request closed without merging**
